spring:
  jwt:
    private-key: dev.key
    public-key: dev.key.pub
    issuer: authsrvc
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka