services:
  # Discovery service (Eureka)
  discovery-service:
    container_name: discovery-service
    hostname: discovery
    build: ./discovery-service
  # Product service
  product-service:
    container_name: product-service
    hostname: product
    build: ./product-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://spring:spring@productdb:27017/productdb?authSource=admin
    depends_on:
      - product-service-mongo
  # Product service database (MongoDB)
  product-service-mongo:
    image: mongo
    container_name: product-service-db
    hostname: productdb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spring
      - MONGO_INITDB_ROOT_PASSWORD=spring
      - MONGO_INITDB_DATABASE=productdb
  # Auth service
  auth-service:
    container_name: auth
    hostname: auth
    build: ./auth-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://spring:spring@authdb:27017/authdb?authSource=admin
    depends_on:
      - auth-service-mongo
    ports:
      - "8080:8080"
  # Auth service database (MongoDB)
  auth-service-mongo:
    image: mongo
    container_name: auth-service-db
    hostname: authdb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spring
      - MONGO_INITDB_ROOT_PASSWORD=spring
      - MONGO_INITDB_DATABASE=authdb
