services:
  # Discovery service (Eureka)
  discovery-service:
    container_name: discovery-service
    hostname: discovery
    build: ./discovery-service
    ports:
      - "8761:8761"
  # Gateway service
  gateway-service:
    container_name: gateway-service
    hostname: gateway
    build: ./gateway-service
    ports:
      - "8443:8443"
  # Product service
  product-service:
    container_name: product-service
    build: ./product-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://spring:spring@productdb:27017/productdb?authSource=admin
    depends_on:
      - product-service-mongo
  # Product service database (MongoDB)
  product-service-mongo:
    image: mongo
    container_name: product-service-db
    hostname: productdb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spring
      - MONGO_INITDB_ROOT_PASSWORD=spring
      - MONGO_INITDB_DATABASE=productdb
  # Auth service
  auth-service:
    container_name: auth-service
    build: ./auth-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://spring:spring@authdb:27017/authdb?authSource=admin
    depends_on:
      - auth-service-mongo
  # Auth service database (MongoDB)
  auth-service-mongo:
    image: mongo
    container_name: auth-service-db
    hostname: authdb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=spring
      - MONGO_INITDB_ROOT_PASSWORD=spring
      - MONGO_INITDB_DATABASE=authdb
  # Order service
  order-service:
    build: ./order-service
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgres://spring:spring@orderdb:5432/orderdb
    depends_on:
      - order-service-postgres
  # Order service database (PostgreSQL)
  order-service-postgres:
    image: postgres
    container_name: order-service-db
    hostname: orderdb
    restart: always
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=spring
      - POSTGRES_DB=orderdb
