server:
  port: 8443
  ssl:
    enabled: true
    key-store-password: password
    key-store: classpath:ks.p12
    key-store-type: PKCS12
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
